export const nameBand = 'QUEENSRŸCHE';
export let nameSongs = [
"SILENT LUCIDITY", /*1*/
"ANYBODY LISTENING?", /*2*/
	"SOMEONE ELSE", /*3*/
	"TAKE HOLD OF THE FLAME", /*4*/
	"ROADS TO MADNESS", /*5*/
	"ANOTHER RAINY NIGHT", /*6*/
	"EYES OF A STRANGER", /*7*/
	"SPREADING THE DISEASE", /*8*/
	"QUEEN OF THE REICH", /*9*/
	"JET CITY WOMAN", /*10*/
	"REVOLUTION CALLING", /*11*/
"OPERATION: MINDCRIME", /*12*/
	"EMPIRE", /*13*/
	"BEST I CAN", /*14*/
	"THE LADY WORE BLACK", /*15*/
	"THE WARNING", /*16*/
	"THE MISSION", /*17*/
"WALK IN THE SHADOWS", /*18*/
	"I DREAM IN INFRARED", /*19*/
	"THE NEEDLE LIES", /*20*/
]